server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/webp,image/apng,image/png,image/jpeg
    min-response-size: 2048

spring:
  devtools:
    restart:
      enabled: true

logging:
  path: ./logs
  config: classpath:logback-config.xml
  level:
    root: info

bms:
  modbus:
    # host: 127.0.0.1
    host: 192.168.99.100
    pcs_port: 502
    other1_port: 503
    other2_port: 504
    bms1_port: 505
    bms2_port: 506
  update:
    interval: 3000